CREATE TABLE Token (
  id BIGSERIAL PRIMARY KEY,
  token VARCHAR(255) UNIQUE NOT NULL,
  token_type VARCHAR(50) NOT NULL,
  revoked BOOLEAN NOT NULL,
  expired BOOLEAN NOT NULL,
  user_id BIGINT,
  FOREIGN KEY (user_id) REFERENCES MoneyUser(id)
);
